# Netlify configuration file for Broadway Corporation website

# Build settings
[build]
  # Directory to publish (the output of the build)
  publish = "frontend/dist"
  # Build command
  command = "cd frontend && pnpm build:netlify"

# Redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers to improve security and caching
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self'; img-src 'self' data:; font-src 'self' data:; connect-src 'self'"

# Cache control for static assets
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables
[context.production.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--version"
  
[context.deploy-preview.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--version" 